// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFd9Xlg0oIgbiZAm7LuVXwwCceuJvBm4k',
    appId: '1:156875006045:web:b1bdeba4734847db9aedb4',
    messagingSenderId: '156875006045',
    projectId: 'creators-39ddf',
    authDomain: 'creators-39ddf.firebaseapp.com',
    storageBucket: 'creators-39ddf.firebasestorage.app',
    measurementId: 'G-CSD71832NL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFkKATz7En5mBOq0NU3dMgN__TpjM4ngc',
    appId: '1:156875006045:android:ab74f67a61cc3c939aedb4',
    messagingSenderId: '156875006045',
    projectId: 'creators-39ddf',
    storageBucket: 'creators-39ddf.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFd9Xlg0oIgbiZAm7LuVXwwCceuJvBm4k',
    appId: '1:156875006045:web:1fa3c431031335c89aedb4',
    messagingSenderId: '156875006045',
    projectId: 'creators-39ddf',
    authDomain: 'creators-39ddf.firebaseapp.com',
    storageBucket: 'creators-39ddf.firebasestorage.app',
    measurementId: 'G-WK03LQ0ZP1',
  );
}
